const statusLabels = {
  livre: 'Livre',
  ocupada: 'Ocupada',
  fechamento: 'Fechamento',
  novo: 'Novo',
  preparando: 'Preparando',
  saiu: 'Saiu para entrega',
  entregue: 'Entregue',
  despachado: 'Despachado',
  'na fila': 'Na fila',
  'em preparo': 'Em preparo',
  finalizando: 'Finalizando',
  finalizado: 'Finalizado',
  pronto: 'Pronto',
  ativo: 'Ativo',
  inativo: 'Inativo',
  alta: 'Alta',
  atrasado: 'Atrasado',
  normal: 'Normal',
  critico: 'Critico',
  baixo: 'Baixo',
  saudavel: 'Saudavel',
  'com-ficha': 'Com ficha',
  'sem-ficha': 'Sem ficha',
  pago: 'Pago',
  dinheiro: 'Dinheiro',
  credito: 'Credito',
  debito: 'Debito',
  pix: 'Pix',
  caderneta: 'Caderneta',
  pendente: 'Pendente',
  em_atendimento: 'Em atendimento',
  convertido: 'Convertido',
  ignorado: 'Ignorado',
  aberto: 'Aberto',
  recebido: 'Recebido',
  admin: 'Administrador',
  atendimento: 'Atendimento',
  cozinha: 'Cozinha',
  garcom: 'Garcom',
}

export function StatusBadge({ status }) {
  const normalized = String(status).toLowerCase()
  return <span className={`status status-${normalized.replaceAll(' ', '-')}`}>{statusLabels[normalized] ?? status}</span>
}
